
# DPMS settings (i.e. when screen off and such)
# standy 0; suspend 300s; Off 300s
exec --no-startup-id xset +dpms dpms 0 300 300

# Start xss-lock on suspend/idle
exec --no-startup-id xss-lock --transfer-sleep-lock -- \
	i3lock \
	  --nofork \
	  --ignore-empty-password \
	  --image='/home/jos/.config/i3/images/lockimage.jpg'

# Manual lock
bindsym Mod4+l exec --no-startup-id \
	i3lock --ignore-empty-password \
		  --image='/home/jos/.config/i3/images/lockimage.jpg' && \
	sleep 0.3 && \
	xset dpms force off
