# Config reload pipeline
bindsym $mod+Shift+r exec ~/.config/i3/build.sh

# Brightness controls
bindsym XF86MonBrightnessUp exec brightnessctl set +5%
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-

# Volume controls
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id wpctl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Lock Screen
bindsym Mod4+l exec --no-startup-id \
i3lock --ignore-empty-password -i ~/.config/i3/images/current_image.jpg --tiling && \
sleep 0.3 && \
xset dpms force off

# No startup id need s othat i3 doesn't show the script running
# Switch to laptop alone
bindsym Mod4+o exec --no-startup-id ~/.config/i3/screen_scripts/laptop.sh

# Switch to dock
bindsym Mod4+d exec --no-startup-id ~/.config/i3/screen_scripts/dock.sh

# Switch to projector
bindsym Mod4+p exec --no-startup-id ~/.config/i3/screen_scripts/project.sh

# switch screen mode
bindsym $mod+F8 exec --no-startup-id ~/.config/i3/screen_scripts/switch_screen.sh

# move workspace to diff screen
bindsym $mod+Shift+m move workspace to output next

# Open the startup apps
bindsym Mod4+s exec --no-startup-id sh -c 'obsidian & sleep 0.1 & todoist & sleep 0.1 & thunderbird & sleep 0.1 & mattermost-desktop'

# Passthrough mode
# enter passthrough mode
bindsym $mod+Shift+p mode "passthrough"

mode "passthrough" {
    # leave passthrough
    bindsym Escape mode "default"
    bindsym $mod+Shift+p mode "default"
}
